In [2]:
import pandas as pd

In [4]:
v_7 = pd.read_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\서울시 통행속도\2021년 07월 서울시 차량통행속도.csv', encoding="EUC-KR")

In [5]:
starbucks_road = pd.read_csv(r"G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_30_50\starbucks_30_50.csv", encoding="EUC-KR")

In [7]:
starbucks_road

,LINK_ID,store_name,store_addr,lat,lot,도로,layer,path
0,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...
1,1220027800,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...
2,1220030700,신사역성일빌딩,서울특별시 강남구 강남대로 584 (논현동)1522-3232,37.514132,127.020563,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...
3,1220030600,신사역성일빌딩,서울특별시 강남구 강남대로 584 (논현동)1522-3232,37.514132,127.020563,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...
4,1220024000,국기원사거리,서울특별시 강남구 테헤란로 125 (역삼동)1522-3232,37.499517,127.031495,테헤란로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...
...,...,...,...,...,...,...,...,...
633,1060005100,묵동,서울특별시 중랑구 동일로 952 1522-3232,37.615368,127.076633,동일로,starbucks_30_rm,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...
634,1060005500,묵동,서울특별시 중랑구 동일로 952 1522-3232,37.615368,127.076633,동일로,starbucks_30_rm,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...
635,1060015100,중화역,"서울특별시 중랑구 봉화산로 35 1,2층1522-3232",37.601709,127.078411,봉화산로,starbucks_30_rm,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...
636,1160003800,구로하이엔드,NaN,NaN,NaN,NaN,NaN,NaN
637,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
starbucks_pop = pd.read_csv(r"G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_join_pop.csv", encoding="EUC-KR")

In [9]:
starbucks_pop

    store_name  지역  구로구     동    도로  유동인구_평균        lat         lot
0      역삼아레나빌딩  서울  강남구  역삼2동   언주로    52263  37.501087  127.043069
1         도곡공원  서울  강남구  역삼2동   도곡로    52263  37.492805  127.041309
2        역삼이마트  서울  강남구  역삼2동   역삼로    52263  37.499367  127.048425
3       논현역사거리  서울  강남구  논현1동  강남대로    41326  37.510178  127.022223
4      신사역성일빌딩  서울  강남구  논현1동  강남대로    41326  37.514132  127.020563
..         ...  ..  ...   ...   ...      ...        ...         ...
551       사가정역  서울  중랑구  면목7동   면목로    20503  37.579594  127.087966
552        상봉역  서울  중랑구  상봉1동   망우로    18510  37.596890  127.086470
553      묵동이마트  서울  중랑구   묵1동   동일로    26575  37.613433  127.077484
554         묵동  서울  중랑구   묵1동   동일로    26575  37.615368  127.076633
555        중화역  서울  중랑구  중화2동  봉화산로    26002  37.601709  127.078411

[556 rows x 8 columns]

In [10]:
pop_join_road = pd.merge(left=starbucks_road, right=starbucks_pop, how='left', left_on='store_name', right_on='store_name')

In [11]:
pop_join_road

,LINK_ID,store_name,store_addr,lat_x,lot_x,도로_x,layer,path,지역,구로구,동,도로_y,유동인구_평균,lat_y,lot_y
0,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,논현1동,강남대로,41326,37.510178,127.022223
1,1220027800,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,논현1동,강남대로,41326,37.510178,127.022223
2,1220030700,신사역성일빌딩,서울특별시 강남구 강남대로 584 (논현동)1522-3232,37.514132,127.020563,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,논현1동,강남대로,41326,37.514132,127.020563
3,1220030600,신사역성일빌딩,서울특별시 강남구 강남대로 584 (논현동)1522-3232,37.514132,127.020563,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,논현1동,강남대로,41326,37.514132,127.020563
4,1220024000,국기원사거리,서울특별시 강남구 테헤란로 125 (역삼동)1522-3232,37.499517,127.031495,테헤란로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,역삼1동,테헤란로,97922,37.499517,127.031495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
633,1060005100,묵동,서울특별시 중랑구 동일로 952 1522-3232,37.615368,127.076633,동일로,starbucks_30_rm,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,중랑구,묵1동,동일로,26575,37.615368,127.076633
634,1060005500,묵동,서울특별시 중랑구 동일로 952 1522-3232,37.615368,127.076633,동일로,starbucks_30_rm,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,중랑구,묵1동,동일로,26575,37.615368,127.076633
635,1060015100,중화역,"서울특별시 중랑구 봉화산로 35 1,2층1522-3232",37.601709,127.078411,봉화산로,starbucks_30_rm,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,중랑구,중화2동,봉화산로,26002,37.601709,127.078411
636,1160003800,구로하이엔드,NaN,NaN,NaN,NaN,NaN,NaN,서울,구로구,구로3동,디지털로26길,39268,37.481618,126.893136
637,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,논현2동,언주로,41704,37.514887,127.035653

In [13]:
pop_join_road.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\pop_join_road.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [16]:
v_202107 = pd.read_csv(r"G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\202107_v.csv", encoding="EUC-KR")

In [17]:
v_202107

,일자,요일,도로명,링크아이디,시점명,종점명,방향,거리,차선수,기능유형구분,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,20210701,목,4.19로,1080012200,아카데미하우스,국립4.19묘지,상행,1179,1,보조간선도로,...,40.66,38.75,49.65,34.83,30.88,41.75,36.70,57.18,53.91,44.74
1,20210701,목,4.19로,1080012800,국립4.19묘지,국립4.19묘지입구,상행,352,2,보조간선도로,...,16.22,15.11,12.69,9.36,9.30,14.78,13.36,18.09,17.09,17.16
2,20210701,목,4.19로,1080012700,국립4.19묘지입구,국립4.19묘지,하행,354,2,보조간선도로,...,19.18,17.31,20.76,18.57,18.79,20.09,20.38,18.14,19.05,22.26
3,20210701,목,4.19로,1080012100,국립4.19묘지,아카데미하우스,하행,1190,1,보조간선도로,...,44.20,44.69,63.16,62.00,48.49,51.04,46.74,50.07,51.82,40.22
4,20210701,목,가락로,1230024700,방이초교,방이동고분군,상행,844,1,기타도로,...,14.95,14.36,13.07,15.40,16.20,18.59,13.41,15.24,16.48,19.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156042,20210731,토,흑석로,1190003703,중앙대학교,성심의집,하행,398,0,기타도로,...,17.72,15.77,15.20,16.68,18.78,17.64,18.30,16.82,17.92,20.47
156043,20210731,토,흑석로,1190003702,성심의집,이화빌라,하행,143,0,기타도로,...,20.66,20.87,22.76,21.55,20.51,20.63,22.15,19.04,18.95,23.49
156044,20210731,토,흑석로,1190003701,이화빌라,이화약국,하행,133,0,기타도로,...,19.08,20.25,22.50,21.25,21.17,21.50,22.75,19.08,16.67,25.88
156045,20210731,토,희우정로,1130016400,망원정사거리,한강공원입구,상행,692,2,기타도로,...,20.86,19.37,20.66,21.44,19.07,20.66,20.96,21.22,21.30,26.91
156046,20210731,토,희우정로,1130016300,한강공원입구,망원정사거리,하행,688,2,기타도로,...,13.87,16.05,19.73,17.32,24.38,16.17,18.97,16.21,19.29,19.58

In [19]:
pop_join_road2 = pd.merge(left=pop_join_road, right=v_202107, how='left', left_on='LINK_ID', right_on='링크아이디')

In [20]:
pop_join_road2

,LINK_ID,store_name,store_addr,lat_x,lot_x,도로_x,layer,path,지역,구로구,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,15.93,17.35,15.82,11.55,12.37,11.28,16.12,17.03,16.63,17.99
1,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,13.62,16.64,14.66,13.30,12.21,NaN,NaN,NaN,NaN,NaN
2,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,18.76,13.04,7.72,6.96,12.24,17.09,17.23,17.86,17.25,19.63
3,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,19.73,19.76,19.50,19.14,19.36,20.96,19.96,19.71,18.21,19.74
4,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,16.81,16.96,15.33,15.73,11.33,15.32,16.14,18.49,18.68,19.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19773,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,6.02,8.20,8.47,7.82,6.63,7.58,11.99,18.29,20.21,21.12
19774,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,7.82,8.25,8.31,7.77,7.22,9.69,12.49,19.79,19.94,24.15
19775,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,7.14,8.39,8.54,7.10,7.45,9.63,11.65,16.52,20.81,23.70
19776,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,6.75,7.13,7.39,7.49,7.48,6.68,10.61,16.32,19.08,23.36
19777,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.58,9.68,13.01,11.37,11.23,14.14,21.25,23.60,23.73,27.07

In [21]:
pop_join_road2.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\pop_join_road2.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [22]:
pop_join_road2

,LINK_ID,store_name,store_addr,lat_x,lot_x,도로_x,layer,path,지역,구로구,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,15.93,17.35,15.82,11.55,12.37,11.28,16.12,17.03,16.63,17.99
1,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,13.62,16.64,14.66,13.30,12.21,NaN,NaN,NaN,NaN,NaN
2,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,18.76,13.04,7.72,6.96,12.24,17.09,17.23,17.86,17.25,19.63
3,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,19.73,19.76,19.50,19.14,19.36,20.96,19.96,19.71,18.21,19.74
4,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,16.81,16.96,15.33,15.73,11.33,15.32,16.14,18.49,18.68,19.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19773,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,6.02,8.20,8.47,7.82,6.63,7.58,11.99,18.29,20.21,21.12
19774,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,7.82,8.25,8.31,7.77,7.22,9.69,12.49,19.79,19.94,24.15
19775,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,7.14,8.39,8.54,7.10,7.45,9.63,11.65,16.52,20.81,23.70
19776,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,6.75,7.13,7.39,7.49,7.48,6.68,10.61,16.32,19.08,23.36
19777,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.58,9.68,13.01,11.37,11.23,14.14,21.25,23.60,23.73,27.07

In [27]:
group_by_07시 = pop_join_road2.groupby('store_name')['07시']

In [32]:
group_by_07시.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\groupby7.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

AttributeError: 'SeriesGroupBy' object has no attribute 'to_csv'

In [42]:
pop_join_road2

,LINK_ID,store_name,store_addr,lat_x,lot_x,도로_x,layer,path,지역,구로구,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,15.93,17.35,15.82,11.55,12.37,11.28,16.12,17.03,16.63,17.99
1,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,13.62,16.64,14.66,13.30,12.21,NaN,NaN,NaN,NaN,NaN
2,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,18.76,13.04,7.72,6.96,12.24,17.09,17.23,17.86,17.25,19.63
3,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,19.73,19.76,19.50,19.14,19.36,20.96,19.96,19.71,18.21,19.74
4,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,16.81,16.96,15.33,15.73,11.33,15.32,16.14,18.49,18.68,19.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19773,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,6.02,8.20,8.47,7.82,6.63,7.58,11.99,18.29,20.21,21.12
19774,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,7.82,8.25,8.31,7.77,7.22,9.69,12.49,19.79,19.94,24.15
19775,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,7.14,8.39,8.54,7.10,7.45,9.63,11.65,16.52,20.81,23.70
19776,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,6.75,7.13,7.39,7.49,7.48,6.68,10.61,16.32,19.08,23.36
19777,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.58,9.68,13.01,11.37,11.23,14.14,21.25,23.60,23.73,27.07

In [43]:
pop_join_road_weekday = pop_join_road2['요일'] == ('월' or '화' or '수' or '목' or '금')

In [45]:
pop_join_road_weekend = pop_join_road2['요일'] == ('토' or '일')

In [46]:
pop_join_road_weekend

0        False
1        False
2         True
3        False
4        False
         ...
19773    False
19774    False
19775    False
19776    False
19777     True
Name: 요일, Length: 19778, dtype: bool

In [47]:
pop_join_road2

,LINK_ID,store_name,store_addr,lat_x,lot_x,도로_x,layer,path,지역,구로구,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,15.93,17.35,15.82,11.55,12.37,11.28,16.12,17.03,16.63,17.99
1,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,13.62,16.64,14.66,13.30,12.21,NaN,NaN,NaN,NaN,NaN
2,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,18.76,13.04,7.72,6.96,12.24,17.09,17.23,17.86,17.25,19.63
3,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,19.73,19.76,19.50,19.14,19.36,20.96,19.96,19.71,18.21,19.74
4,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,16.81,16.96,15.33,15.73,11.33,15.32,16.14,18.49,18.68,19.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19773,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,6.02,8.20,8.47,7.82,6.63,7.58,11.99,18.29,20.21,21.12
19774,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,7.82,8.25,8.31,7.77,7.22,9.69,12.49,19.79,19.94,24.15
19775,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,7.14,8.39,8.54,7.10,7.45,9.63,11.65,16.52,20.81,23.70
19776,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,6.75,7.13,7.39,7.49,7.48,6.68,10.61,16.32,19.08,23.36
19777,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.58,9.68,13.01,11.37,11.23,14.14,21.25,23.60,23.73,27.07

In [51]:
weekday = pop_join_road2[pop_join_road_weekday]

In [52]:
weekday

,LINK_ID,store_name,store_addr,lat_x,lot_x,도로_x,layer,path,지역,구로구,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
4,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,16.81,16.96,15.33,15.73,11.33,15.32,16.14,18.49,18.68,19.62
11,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,17.27,16.63,16.76,14.79,14.22,16.76,18.50,19.34,17.41,18.84
18,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,18.60,17.26,15.07,12.38,7.66,12.85,17.73,19.59,18.39,20.19
25,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,12.57,13.97,13.01,13.58,13.18,15.58,19.69,19.93,18.03,18.80
35,1220027800,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,17.72,12.87,10.95,12.02,10.50,14.01,20.34,22.43,24.41,26.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19741,1160003800,구로하이엔드,NaN,NaN,NaN,NaN,NaN,NaN,서울,구로구,...,30.06,29.43,30.41,25.49,18.30,25.12,31.31,30.52,31.80,33.34
19751,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,8.75,8.66,8.19,6.94,8.13,8.43,11.72,15.85,18.98,24.55
19758,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.65,9.32,9.34,8.39,8.43,10.01,14.09,18.47,19.21,25.44
19765,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.78,8.39,7.28,7.20,6.51,7.34,11.43,12.50,17.77,21.54
19772,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.57,8.81,8.99,7.38,6.48,10.90,14.04,13.45,19.65,24.98

In [54]:
weekend = pop_join_road2[pop_join_road_weekend]

In [55]:
weekend.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\weekend.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [56]:
weekday.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\weekday.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [57]:
weekday

,LINK_ID,store_name,store_addr,lat_x,lot_x,도로_x,layer,path,지역,구로구,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
4,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,16.81,16.96,15.33,15.73,11.33,15.32,16.14,18.49,18.68,19.62
11,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,17.27,16.63,16.76,14.79,14.22,16.76,18.50,19.34,17.41,18.84
18,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,18.60,17.26,15.07,12.38,7.66,12.85,17.73,19.59,18.39,20.19
25,1220027900,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,12.57,13.97,13.01,13.58,13.18,15.58,19.69,19.93,18.03,18.80
35,1220027800,논현역사거리,서울특별시 강남구 강남대로 538 (논현동)1522-3232,37.510178,127.022223,강남대로,50m제거,G:/내 드라이브/2021 공공빅데이터 청년인턴/프로젝트/데이터/starbucks_...,서울,강남구,...,17.72,12.87,10.95,12.02,10.50,14.01,20.34,22.43,24.41,26.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19741,1160003800,구로하이엔드,NaN,NaN,NaN,NaN,NaN,NaN,서울,구로구,...,30.06,29.43,30.41,25.49,18.30,25.12,31.31,30.52,31.80,33.34
19751,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,8.75,8.66,8.19,6.94,8.13,8.43,11.72,15.85,18.98,24.55
19758,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.65,9.32,9.34,8.39,8.43,10.01,14.09,18.47,19.21,25.44
19765,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.78,8.39,7.28,7.20,6.51,7.34,11.43,12.50,17.77,21.54
19772,1220031300,서울세관사거리,NaN,NaN,NaN,NaN,NaN,NaN,서울,강남구,...,9.57,8.81,8.99,7.38,6.48,10.90,14.04,13.45,19.65,24.98

In [68]:
weekday = weekday.groupby(['store_name']).mean()

In [69]:
weekday.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\weekday_mean.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [70]:
weekend = weekend.groupby(['store_name']).mean()

In [71]:
weekend.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\weekend_mean.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [102]:
cluster8 = pd.read_csv(r"G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_cluster8.csv", encoding="EUC-KR")

In [117]:
starbucks_group0 = cluster8['cluster'] == 0
starbucks_group0 = cluster8[starbucks_group0]
starbucks_group0.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_group0.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [118]:
starbucks_group1 = cluster8['cluster'] == 1
starbucks_group1 = cluster8[starbucks_group1]
starbucks_group1.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_group1.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [119]:
starbucks_group2 = cluster8['cluster'] == 2
starbucks_group2 = cluster8[starbucks_group2]
starbucks_group2.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_group2.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [120]:
starbucks_group3 = cluster8['cluster'] == 3
starbucks_group3 = cluster8[starbucks_group3]
starbucks_group3.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_group3.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [121]:
starbucks_group4 = cluster8['cluster'] == 4
starbucks_group4 = cluster8[starbucks_group4]
starbucks_group4.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_group4.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [122]:
starbucks_group5 = cluster8['cluster'] == 5
starbucks_group5 = cluster8[starbucks_group5]
starbucks_group5.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_group5.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [123]:
starbucks_group6 = cluster8['cluster'] == 6
starbucks_group6 = cluster8[starbucks_group6]
starbucks_group6.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_group6.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [124]:
starbucks_group7 = cluster8['cluster'] == 7
starbucks_group7 = cluster8[starbucks_group7]
starbucks_group7.to_csv(r'G:\내 드라이브\2021 공공빅데이터 청년인턴\프로젝트\데이터\starbucks_group7.csv', sep=',', na_rep='NaN', encoding='EUC-KR')

In [112]:
weekday

,LINK_ID,lat_x,lot_x,유동인구_평균,lat_y,lot_y,일자,링크아이디,거리,차선수,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
store_name,,,,,,,,,,,,,,,,,,,,,
KG타워,1.010009e+09,37.563528,126.969144,24141.0,37.563528,126.969144,20210715.5,1.010009e+09,501.0,4.000000,...,19.04000,17.76250,17.35250,20.220000,16.697500,18.337500,25.667500,27.3925,29.562500,33.7100
SSG마켓도곡R,1.220014e+09,37.490298,127.054895,30953.0,37.490298,127.054895,20210715.5,1.220014e+09,564.0,4.000000,...,20.79625,18.24375,17.60625,16.987500,16.922500,20.532500,24.058750,25.2875,27.466250,32.0975
가락시장역,1.230010e+09,37.494299,127.121354,37909.0,37.494299,127.121354,20210715.5,1.230010e+09,483.0,2.666667,...,16.68250,15.97500,15.37000,14.966667,15.003333,17.551667,18.474167,19.3625,20.484167,22.8600
가재울뉴타운,1.120008e+09,37.574984,126.916444,20391.0,37.574984,126.916444,20210715.5,1.120008e+09,833.0,2.000000,...,15.80750,16.30000,15.74500,16.505000,15.850000,16.750000,15.245000,16.3125,18.525000,18.3075
강남R,1.220023e+09,37.497711,127.028439,97922.0,37.497711,127.028439,20210715.5,1.220023e+09,323.0,4.000000,...,21.94000,21.24000,22.97000,24.545000,24.092500,25.470000,27.287500,26.1675,23.187500,25.6400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
화곡동,1.140038e+09,37.540512,126.837241,47359.0,37.540512,126.837241,20210715.5,1.140038e+09,1315.0,3.000000,...,15.10750,15.48750,14.79750,14.600000,15.475000,15.550000,17.772500,18.3650,20.007500,20.7800
환구단,1.010010e+09,37.564448,126.979157,24141.0,37.564448,126.979157,20210715.5,1.010010e+09,137.0,3.000000,...,21.65250,22.23000,23.12500,23.330000,23.882500,24.332500,25.370000,26.2150,25.155000,27.9300
황학사거리,1.018018e+09,37.567644,127.023697,30053.0,37.567644,127.023697,20210715.5,1.018018e+09,444.2,1.600000,...,17.41350,16.84500,16.73250,16.408000,16.640500,17.161000,17.197000,17.2005,19.044000,20.6920
황학캐슬,1.010019e+09,37.571240,127.022905,12939.0,37.571240,127.022905,20210715.5,1.010019e+09,429.0,2.000000,...,13.74750,12.52000,11.85750,11.650000,12.592500,15.550000,15.840000,16.3875,18.240000,21.2450
효창공원앞역,1.020014e+09,37.539305,126.963060,10216.0,37.539305,126.963060,20210715.5,1.020014e+09,462.0,3.000000,...,20.00750,20.05500,18.87750,18.567500,16.612500,16.302500,17.322500,17.8725,20.095000,21.8300

In [116]:
cluster8 = pd.merge(left=cluster8, right=weekday, how='left', left_on='store_name', right_on='store_name')

In [115]:
weekday_cluster

,store_name,유동인구_평균_x,차선수_x,cluster,LINK_ID,lat_x,lot_x,유동인구_평균_y,lat_y,lot_y,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,KG타워,24141.0,4.000000,7,1.010009e+09,37.563528,126.969144,24141.0,37.563528,126.969144,...,19.04000,17.76250,17.35250,20.220000,16.697500,18.337500,25.667500,27.3925,29.562500,33.7100
1,SSG마켓도곡R,30953.0,4.000000,7,1.220014e+09,37.490298,127.054895,30953.0,37.490298,127.054895,...,20.79625,18.24375,17.60625,16.987500,16.922500,20.532500,24.058750,25.2875,27.466250,32.0975
2,가락시장역,37909.0,2.666667,1,1.230010e+09,37.494299,127.121354,37909.0,37.494299,127.121354,...,16.68250,15.97500,15.37000,14.966667,15.003333,17.551667,18.474167,19.3625,20.484167,22.8600
3,가재울뉴타운,20391.0,2.000000,5,1.120008e+09,37.574984,126.916444,20391.0,37.574984,126.916444,...,15.80750,16.30000,15.74500,16.505000,15.850000,16.750000,15.245000,16.3125,18.525000,18.3075
4,강남R,97922.0,4.000000,2,1.220023e+09,37.497711,127.028439,97922.0,37.497711,127.028439,...,21.94000,21.24000,22.97000,24.545000,24.092500,25.470000,27.287500,26.1675,23.187500,25.6400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,화곡동,47359.0,3.000000,3,1.140038e+09,37.540512,126.837241,47359.0,37.540512,126.837241,...,15.10750,15.48750,14.79750,14.600000,15.475000,15.550000,17.772500,18.3650,20.007500,20.7800
289,환구단,24141.0,3.000000,6,1.010010e+09,37.564448,126.979157,24141.0,37.564448,126.979157,...,21.65250,22.23000,23.12500,23.330000,23.882500,24.332500,25.370000,26.2150,25.155000,27.9300
290,황학사거리,30053.0,1.600000,5,1.018018e+09,37.567644,127.023697,30053.0,37.567644,127.023697,...,17.41350,16.84500,16.73250,16.408000,16.640500,17.161000,17.197000,17.2005,19.044000,20.6920
291,황학캐슬,12939.0,2.000000,5,1.010019e+09,37.571240,127.022905,12939.0,37.571240,127.022905,...,13.74750,12.52000,11.85750,11.650000,12.592500,15.550000,15.840000,16.3875,18.240000,21.2450
292,효창공원앞역,10216.0,3.000000,6,1.020014e+09,37.539305,126.963060,10216.0,37.539305,126.963060,...,20.00750,20.05500,18.87750,18.567500,16.612500,16.302500,17.322500,17.8725,20.095000,21.8300